### ISSUE TITLE
[partner] tạo drop down cho câu trả lời của câu hỏi. 

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/studentlifecare#103]
As a partner, Tôi có thể click vào câu hỏi và câu trả lời cho câu hỏi đó sẽ được drop down xuống, khi click vào câu hỏi khác thì câu trả lời của câu trước sẽ được kéo lên

**Comment by Palmdate** [comment]
![Screenshot from 2016-03-04 17:42:13.png](https://files.zenhub.io/56d966e09b26fbbb098e6951)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
![Screenshot from 2016-03-04 17:43:04.png](https://files.zenhub.io/56d966e49b26fbbb098e6952)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
