### ISSUE TITLE
[partner] xem các thông tin quản lý liên quan tới khách hàng và học sinh

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/studentlifecare#106]
as a partner, Tôi có thể xem: ngày đăng ký, tên học sinh, chú thích (dịch vụ đăng ký), tổng thu của khách hàng, tiền hoa hồng, trạng thái của việc thanh toán (không phải trạng thái của học sinh) refre as page " lich su giao dich".

**Comment by Palmdate** [comment]
![Screenshot from 2016-03-04 14:14:18.png](https://files.zenhub.io/56d937269b26fbbb098e6651)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
