### ISSUE TITLE
[partner] tao pop up trang detail cua sinh vien

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/studentlifecare#74]
As a partner, Tôi có thể xem thông tin chi tiết của học sinh bằng cách click vào tên từng học sinh (sẽ hiện ra một bảng popup thông tin của học sinh)

**Comment by Palmdate** [comment]
![Screenshot from 2016-02-25 17:33:50.png](https://files.zenhub.io/56ced8d934ab40f92bc771f8)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
![Screenshot from 2016-02-25 17:34:26.png](https://files.zenhub.io/56ced8d934ab40f92bc771f9)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
![Screenshot from 2016-02-25 17:34:13.png](https://files.zenhub.io/56ced8d934ab40f92bc771fa)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
