### ISSUE TITLE
[partner] Sắp xếp danh sách sinh viên. 

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/studentlifecare#84]
As a partner, Tôi có thể sắp xếp theo thứ tự A-Z theo tên của học sinh (mũi tên drop down bên cạnh tên học sinh trong invision), hoặc sắp xếp theo thứ tự thời gian(sớm nhất/ muộn nhất) của ngày đến/ ngày đăng ký (mũi tên drop down bên cạnh ngày đến, ngày đăng ký)

**Comment by Palmdate** [comment]
done
