### ISSUE TITLE
[partner] Sắp xếp danh sách sinh viên theo thứ tự abc, theo status.

### ISSUE THREAD

**Issue by irene-ng** [GoldenOwlAsia/studentlifecare#86]
As a partner, Tôi có thể sắp xếp theo thứ tự thời gian của ngày đăng ký, hoặc thứ tự ABC của tên học sinh (mũi tên drop down), hoặc sắp xếp theo trạng thái đã thanh toán hoặc chưa thanh toán

**Comment by Palmdate** [comment]
done.


![Screenshot from 2016-03-04 14:14:18.png](https://files.zenhub.io/56d9379a9b26fbbb098e6653)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
